[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "plotly>=6.1.1",
    "scipy>=1.15.3",
    "streamlit>=1.45.1",
    "sympy>=1.14.0",
]
